name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Berechtigung zum Erstellen von Releases

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Validate and build the project
        run: mvn clean compile

      - name: Generate jOOQ sources
        run: mvn generate-sources

      - name: Run tests
        run: mvn test

      - name: Package the application
        run: mvn package

      - name: Check if commit has 'submission' tag
        id: check_tag
        run: |
          TAG=$(git tag --points-at HEAD | grep 'submission' || echo "")
          if [[ -z "$TAG" ]]; then
            TAG="v$(date +'%Y%m%d-%H%M%S')"
            TITLE="Release $TAG"
          else
            TITLE="Abgabeversion"
          fi
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
          echo "RELEASE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TITLE }}
          draft: false
          prerelease: false
          files: target/*.jar