name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Validate and build the project
      run: mvn clean compile

    - name: Generate jOOQ sources
      run: mvn generate-sources

    - name: Run tests
      run: mvn test

    - name: Package the application
      run: mvn package

    - name: Determine Version
      id: get_version
      run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Create GitHub Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.version }}
        release_name: Release v${{ env.version }}
        draft: false
        prerelease: false
        files: target/*.jar
